
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_ERRNO_H
#define DCE_HEADER_ERRNO_H
// TODO add extern "C" ?
#include <errno.h>
#include <stdarg.h> // just in case there is an ellipsis
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int * dce___errno_location () noexcept ;

#define dce_errno (*dce___errno_location ())
#define dce_h_errno (*dce__h_errno_location ())

/* int * dce___errno_location (void); */
/* int * dce___h_errno_location (void); */


#define __dce_set_errno(_errno) errno = Current()->err = _errno

#ifdef __cplusplus
}
#endif
#endif
