import os
import ns3waf
from collections import namedtuple
from waflib import Logs, Errors, Utils

def options(opt):
    opt.add_option('--disable-examples', help='Disable compilation of examples',
                   dest='enable_examples', action='store_false',
                   default=True)

