version: 2
general:
  artifacts:

# machine:
#   post:
  # - pyenv global 3.6.0


do_steps: &do_steps
 steps:
  - restore_cache:
      keys: 
        - v1-code-tree-shallow-{{ .Branch }}
  # - restore_cache:
  #     keys: 
  #       # have to be careful here the cache restores the files with the patch on
  #       - v2-bake-tree-cache-{{ .Branch }}
  - run:
      name: checkout build tree
      command: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        if ! [ -d .git ]; then
          git clone $CIRCLE_REPOSITORY_URL .;
        fi
        if [[ $CIRCLE_BRANCH == pull/* ]]; then
           git fetch origin $CIRCLE_BRANCH/head;
        else
           git fetch origin $CIRCLE_BRANCH;
        fi
        git reset --hard $CIRCLE_SHA1

  - run:
      name: enable python3
      command: |
        sudo apt-get install -y python3.4-venv
        python3 -m venv $HOME/venv
        . ${HOME}/venv/bin/activate

  - run:
      name: download bake and codes
      environment:
      command: |
        . ${HOME}/venv/bin/activate
        if [ -z "${BAKE_BRANCH}" ] ; then export BAKE_BRANCH="master" ; fi
        if [ -z "${BAKE_MOD_VERSION}" ] ; then export BAKE_MOD_VERSION="dev" ; fi

        # The cache saves the patched files making the application of the same patch
        # a failure. We remove patched programs so that they get reinstalled
        rm -rf ${HOME}/source/iputils  ${HOME}/source/iperf
        cd "$HOME" && git clone -b ${BAKE_BRANCH} git://github.com/direct-code-execution/bake ./bake
        cd "$HOME" && ./bake/bake.py configure -e dce-umip-${BAKE_MOD_VERSION} -e dce-linux-${BAKE_MOD_VERSION}
        cd "$HOME" && strace -olog_download -f ./bake/bake.py download -vvv && strace -log_update -f ./bake/bake.py update -vvv

  - save_cache:
      key: v1-code-tree-shallow-{{ .Branch }}-{{ epoch }}
      paths:
        - /home/ns3dce/project/.git

  - save_cache:
      key: v2-bake-tree-cache-{{ .Branch }}-{{ epoch }}
      paths:
        - /home/ns3dce/source
        # - /home/ns3dce/source/quagga
        # - /home/ns3dce/source/net-next-nuse
        # - /home/ns3dce/source/libaspect
        # - /home/ns3dce/source/netanim

  - run: mkdir -p /home/ns3dce/.ccache
  - restore_cache:
      key: compiler-cache-{{ .Environment.CIRCLE_JOB }}
  - run: ccache -M 5.0G
  - run:
      name: build dce
      command: |
        . ${HOME}/venv/bin/activate

        # bake installs the master branch hence DCE will be install $CIRCLE_BRANCH
        cd ${HOME}/source/ns-3-dce && git remote add local "$HOME/project" && \
            git fetch local -a && git reset --hard $CIRCLE_SHA1
        cd "$HOME" && ./bake/bake.py build -j1 -vvv

  - save_cache:
     paths:
       - /home/ns3dce/.ccache
     key: compiler-cache-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
  - run: cd ${HOME}/source/ns-3-dce && ./test.py -r
  - run:
      name: save test results
      environment:
        TERM: dumb
      command: |
        mkdir -p ~/junit/
        find ~/source -type f -name results.xml -exec cp {} ~/junit/ \;
        find ~/source -type f -name xml2junit.xsl -exec cp {} ~/junit/ \;
        cp -rpf ~/source/ns-3-dce/testpy-output ~/
        saxonb-xslt ~/junit/results.xml ~/junit/xml2junit.xsl  > ~/junit/junit-results.xml
      when: always
  - store_test_results:
      path: ~/junit
  - store_artifacts:
      path: ~/junit
      path: ~/testpy-output

## Customize the test machine
jobs:
  ubuntu14.04:
   docker:
     - image: ns3dce/ubuntu14.04:0.1
   environment:
   <<: *do_steps

  ubuntu16.04:
   docker:
     - image: ns3dce/ubuntu16.04:0.1
   environment:
   <<: *do_steps

  ubuntu17.04:
   docker:
     - image: ns3dce/ubuntu17.04:0.1
   environment:
   <<: *do_steps

  fedora26:
   docker:
     - image: ns3dce/fedora26:0.1
   environment:
   <<: *do_steps

  fedora27:
   docker:
     - image: ns3dce/fedora27:0.1
   environment:
   <<: *do_steps

  # not yet released (171228)
  fedora28:
   docker:
     - image: ns3dce/fedora28:0.1
   environment:
   <<: *do_steps


workflows:
  version: 2
  build:
    jobs:
     - ubuntu14.04
     # - ubuntu16.04
     # - ubuntu17.04
     # - fedora26
     # - fedora27
  nightly_workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *" # run at 1am UTC
          filters:
            branches:
              only:
                - fix-valgrind-test
    jobs:
      - ubuntu14.04_valgrind
